#include <bits/stdc++.h>
#include <fstream>
#include "rvms.hpp"

using namespace std;

double pdfBinomialRecursive(long n, double p, long x)
{
    if(x == 0)
        return pow((1-p), n);

    double ans = ((n - x + 1) * p)/(x * (1 - p));
    return ans * pdfBinomialRecursive(n, p, x-1);
}

double pdfPoissonRecursive(double m, long x)
{
    if(x == 0)
        return exp(-1*m);

    double ans = (double)m/x;
    return ans * pdfPoissonRecursive(m, x-1);
}

main(){
    double pdf;

    ofstream f1;
    f1.open("pdfs_libs.txt");
    f1 << "PDF's generated by libs" << endl;

    f1 << endl << "Poisson PDF" << endl;
    for(int i = 0; i <= 25; i++)
    {
        pdf = pdfPoisson(1.0, i);
        f1 << fixed << setprecision(5) << pdf << endl;
    }

    f1 << endl << "Binomial PDF" << endl;
    for(int i = 0; i <= 25; i++)
    {
        pdf = pdfBinomial(25, 0.04, i);
        f1 << fixed << setprecision(5) << pdf << endl;
    }
    f1.close();

    ofstream f2;
    f2.open("pdfs_recursion.txt");
    f2 << "PDF's generated by recursion" << endl;

    f2 << endl << "Poisson PDF" << endl;
    for(int i = 0; i <= 25; i++)
    {
        pdf = pdfPoissonRecursive(1.0, i);
        f2 << fixed << setprecision(5) << pdf << endl;
    }

    f2 << endl << "Binomial PDF" << endl;
    for(int i = 0; i <= 25; i++)
    {
        pdf = pdfBinomialRecursive(25, 0.04, i);
        f2 << fixed << setprecision(5) << pdf << endl;
    }
    f2.close();
}
